from pydantic import BaseModel, Field
from typing import Optional

# 📝 Pydantic Schema for incoming HTTP POST request payload from mobile app
class ReframeRequest(BaseModel):
    input_text: str = Field(
        min_length=1,
        description="Raw problem, stress point, or thought entered by the user"
    )
    target_language: str = Field(
        default="auto",
        description="Target ISO language code (default 'auto' for auto-detection, e.g. 'uk', 'es', 'en')"
    )

# 📦 Pydantic Schema for outgoing HTTP response payload returned to mobile app
class ReframeResponse(BaseModel):
    is_safe: bool = Field(
        description="True if input passed all safety checks, False if refused"
    )
    safety_category: str = Field(
        default="none",
        description="Category of safety rule (e.g., 'none', 'self_harm', 'crime')"
    )
    reframed_text: Optional[str] = Field(
        default=None,
        description="The positive perspective text generated by AI engine"
    )
    language: str = Field(
        default="auto",
        description="Target/detected language code for this reframed response"
    )
    crisis_triggered: bool = Field(
        default=False,
        description="True if self-harm rules triggered Crisis Shield card"
    )
    emergency_hotline: Optional[str] = Field(
        default=None,
        description="Hotline number (e.g., '988') if crisis was triggered"
    )

# 🚩 GenAI Objectionable Content Report Schemas (Apple 1.2 & Google Play GenAI Policy)
class ReportRequest(BaseModel):
    content_snippet: str = Field(
        min_length=1,
        description="Reframed AI text or problem snippet being reported"
    )
    reason: str = Field(
        description="Reason for report: inappropriate, harmful, offensive, inaccurate, other"
    )
    details: Optional[str] = Field(
        default=None,
        description="Optional additional context or comments provided by user"
    )
    reframe_id: Optional[str] = Field(
        default=None,
        description="Optional ID of the associated ReframeRecord"
    )

class ReportResponse(BaseModel):
    id: str = Field(description="Unique UUID of the generated report record")
    status: str = Field(default="received", description="Status of the report")
    message: str = Field(
        default="Report submitted successfully for safety review.",
        description="Confirmation message returned to user"
    )

# 🗑️ In-App Account Deletion Response Schema (Apple 5.1.1(v) & Google Play Data Deletion)
class DeleteAccountResponse(BaseModel):
    detail: str = Field(
        default="Account and all associated personal data permanently deleted.",
        description="Confirmation details of cascading data deletion"
    )
    user_id: str = Field(description="ID of the deleted user")
    deleted_records_count: int = Field(
        description="Total number of reframing history records purged"
    )

# 🌐 Public Web Account Deletion Request Schema (Google Play Data Safety Mandate)
class WebDeleteAccountRequest(BaseModel):
    email: str = Field(
        min_length=3,
        description="Registered user email address for deletion request"
    )
    reason: Optional[str] = Field(
        default=None,
        description="Optional reason for account deletion"
    )

class WebDeleteAccountResponse(BaseModel):
    status: str = Field(
        default="completed",
        description="Status of the deletion request (completed or unverified)"
    )
    message: str = Field(
        description="User-facing confirmation message explaining data purge"
    )
    account_found: bool = Field(
        description="Whether a registered account was located and purged"
    )


