from pydantic import BaseModel, Field
from typing import Optional

# 📝 Pydantic Schema for incoming HTTP POST request payload from mobile app
class ReframeRequest(BaseModel):
    input_text: str = Field(
        ...,
        min_length=1,
        description="Raw problem, stress point, or thought entered by the user"
    )

# 📦 Pydantic Schema for outgoing HTTP response payload returned to mobile app
class ReframeResponse(BaseModel):
    is_safe: bool = Field(
        ...,
        description="True if input passed all safety checks, False if refused"
    )
    safety_category: str = Field(
        default="none",
        description="Category of safety rule (e.g., 'none', 'self_harm', 'crime')"
    )
    reframed_text: Optional[str] = Field(
        default=None,
        description="The positive perspective text generated by Gemini AI"
    )
    crisis_triggered: bool = Field(
        default=False,
        description="True if self-harm rules triggered Crisis Shield card"
    )
    emergency_hotline: Optional[str] = Field(
        default=None,
        description="Hotline number (e.g., '988') if crisis was triggered"
    )
