import 'package:flutter/material.dart';
import '../../theme/app_colors.dart';
import '../../theme/app_typography.dart';

/// ⚖️ Legal & Medical Disclaimer Dialogs (App Store Guideline 1.4.1, 5.1.1 & Google Play Health Policy)
class LegalInfoDialog extends StatelessWidget {
  final String title;
  final String content;

  const LegalInfoDialog({
    super.key,
    required this.title,
    required this.content,
  });

  static void showMedicalDisclaimer(BuildContext context) {
    showDialog(
      context: context,
      builder: (ctx) => const LegalInfoDialog(
        title: '🩺 Medical & Wellness Disclaimer',
        content: '''
Silver Lining AI is an artificial intelligence-powered self-reflection and cognitive reframing tool.

IMPORTANT NOTICE:
1. Not Medical Care: Silver Lining is NOT a licensed healthcare provider, medical clinic, or therapy service. The app does not provide medical diagnosis, clinical treatment, or psychological therapy.
2. Self-Reflection Only: The reframed perspectives provided by our AI are meant solely for personal perspective-taking, positive mindset support, and mindfulness.
3. Crisis Assistance: If you are experiencing a mental health emergency, acute distress, or thoughts of self-harm, please immediately contact emergency services or call/text the 988 Suicide & Crisis Lifeline (US/Canada) or your local emergency number.
4. Professional Consultation: Never disregard professional medical or psychiatric advice because of information generated by this application.
''',
      ),
    );
  }

  static void showPrivacyPolicy(BuildContext context) {
    showDialog(
      context: context,
      builder: (ctx) => const LegalInfoDialog(
        title: '🔒 Privacy Policy',
        content: '''
Effective Date: October 1, 2026

At Silver Lining AI, we respect your privacy and are committed to protecting your personal data:

1. Data Collection:
- Guest Users: No accounts, no database storage. Your thought reframings are processed ephemerally and saved strictly on your local device.
- Registered Users: When you create an account, we store your email address and synced reflections in an encrypted PostgreSQL database.

2. Generative AI Processing:
- Inputs are processed solely to generate reframings and evaluate safety. Your personal thoughts are never sold to advertisers or third-party brokers.

3. Account & Data Deletion:
- In full compliance with Apple Guideline 5.1.1(v) and Google Play policies, you may permanently delete your account and all associated reflection history at any time directly in the app.

4. Security:
- All network communications are encrypted via TLS/HTTPS, and authentication tokens are verified using asymmetric cryptographic keys.
''',
      ),
    );
  }

  static void showTermsOfService(BuildContext context) {
    showDialog(
      context: context,
      builder: (ctx) => const LegalInfoDialog(
        title: '📜 Terms of Service & EULA',
        content: '''
Effective Date: October 1, 2026

Welcome to Silver Lining AI. By accessing or using our application, you agree to these Terms:

1. Permitted Use:
- Silver Lining is intended to foster constructive perspective reframing for everyday stress and life challenges.

2. Zero-Tolerance for Abusive Content:
- In accordance with Apple Guideline 1.2 and Google Play GenAI policies, users are strictly prohibited from submitting prompts promoting self-harm, illegal acts, violent crime, severe harassment, or abuse.
- Our multi-layered safety guardrails block prohibited inputs.

3. AI Limitations:
- The perspectives generated by AI are automated suggestions. Silver Lining does not warrant that AI outputs will meet your exact requirements or be entirely error-free.

4. Account Termination:
- You may terminate your account at any time via the in-app Delete Account function.
''',
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      backgroundColor: AppColors.surface,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(18)),
      title: Text(
        title,
        style: const TextStyle(color: Colors.white, fontSize: 18, fontWeight: FontWeight.bold),
      ),
      content: SingleChildScrollView(
        child: Text(
          content.trim(),
          style: AppTypography.body.copyWith(color: Colors.white70, height: 1.45, fontSize: 13),
        ),
      ),
      actions: [
        ElevatedButton(
          style: ElevatedButton.styleFrom(
            backgroundColor: AppColors.primary,
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
          ),
          onPressed: () => Navigator.of(context).pop(),
          child: const Text('Understood', style: TextStyle(color: Colors.white)),
        ),
      ],
    );
  }
}
